# Generated by Django 3.2.13 on 2022-06-25 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
