# Generated by Django 3.2.13 on 2022-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_final_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_inicio_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='leitor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
